#!/bin/bash
#SBATCH -p short
#SBATCH --job-name="Rinn Lab RNAseq test"
#SBATCH --mail-type=ALL
#SBATCH --mail-user=michael.smallegan@colorado.edu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=6gb
#SBATCH --time=12:00:00
#SBATCH --output=./log/slurm.log
#SBATCH --error=./log/slurm.err

pwd; hostname; date

export PATH=/opt/singularity/3.1.1/bin:$PATH

nextflow \
  -log ./log/nextflow.log \
  run main.nf \
  -resume \
  -with-report ./reports/rnaseq_test.html \
  -with-dag ./reports/rnaseq_test_dag.pdf

date
